# Generated by Django 3.2.20 on 2023-08-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
